### ISSUE TITLE
Float values in metadata json file causes TypeError due to attempt to concatenate str and float

### ISSUE THREAD

**Issue by pchengi** [EC-Earth/cmor-fixer#45]
cat recipe.json                                                    
{
    "branch_time_in_parent": 29218.0
}
singularity run --bind /home/pchengi/cmor-fixer_env:/mnt cmorfixerenv.simg

/opt/cmor_fixer/cmor-fixer/cmor-fixer.py /mnt/metadatafix_test --verbose --olist /home/pchengi/outputdir --npp 1 --meta /mnt/metadatafix_test/recipe.json

2024-11-07 12:09:11 INFO:cmor-fixer.py: Setting metadata field branch_time_in_parent to 29218.0 in /mnt/metadatafix_test/siconca_SIday_EC-Earth3-Veg_historical_r1i1p1f1_gr_18800101-18801231.nc
Traceback (most recent call last):
  File "/opt/cmor_fixer/cmor-fixer/cmor-fixer.py", line 388, in <module>
    main()
    ~~~~^^
  File "/opt/cmor_fixer/cmor-fixer/cmor-fixer.py", line 362, in main
    worker(fullpath)
    ~~~~~~^^^^^^^^^^
  File "/opt/cmor_fixer/cmor-fixer/cmor-fixer.py", line 247, in process_file
    modified = fix_file(path, write, keepid, forceid, metadata, add_attributes)
  File "/opt/cmor_fixer/cmor-fixer/cmor-fixer.py", line 221, in fix_file
    log_overview_modified_attributes=log_overview_modified_attributes+'Set ' + attname + ' to ' + attval + '. '
                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
TypeError: can only concatenate str (not "float") to str

**Comment by treerink** [comment]
Thanks @pchengi. Merged.
